### ISSUE TITLE
Missing global_tracker.xml

### ISSUE THREAD

**Issue by djabi** [googlesamples/google-services#220] opened 2016-05-16 00:35 UTC
global_tracker.xml file is missing. The project doesn't compile when open in Android Studio 2.1. Ideally GA will be configured from code so this fragile dependency is not needed.

https://github.com/googlesamples/google-services/blob/master/android/analytics/app/src/main/java/com/google/samples/quickstart/analytics/AnalyticsApplication.java#L39

**Comment by samtstern** [comment] 2016-05-16 15:28
`global_tracker.xml` comes from `google-services.json` which is required to run this sample because of the `google-services` plugin applied by the line `apply com.google.gms.google-services` in `build.gradle`.  You can use Google Analytics without this plugin and therefore without the JSON file however for the purposes of this sample repository we choose to use the JSON file for configuration as that is best practice.

Closing the issue because this is working as intended.  If you are missing `global_tracker` and you believe you have properly configured the JSON file, please re-open.

**Closed by samtstern** 2016-05-16 15:28 UTC
