### ISSUE TITLE
Error login in with Google Error Domain=com.google.GIDSignIn Code=-2 "keychain error" UserInfo={NSLocalizedDescription=keychain error}

### ISSUE THREAD

**Issue by jlubeck** [googlesamples/google-services#82] opened 2015-10-07 16:58 UTC
Completely randomly I'm getting this error when calling 

[[GIDSignIn sharedInstance] signIn];

What's the reason of this on what can I do to fix it?

**Comment by edwardIshaq** [comment] 2015-10-19 18:44
same here, did you happen to find a solution for this ?

**Comment by jlubeck** [comment] 2015-10-19 18:46
Not yet... looking forward on a response from the team

**Comment by kraghavan-cc** [comment] 2015-10-19 21:16
I am seeing this same problem. Not sure how should we proceed. One interesting observation is that if I use the Google's GIDSignInButton I don't see this issue. Only if  I use custom sign in button , I see this problem.

**Comment by edwardIshaq** [comment] 2015-10-19 21:17
I noticed the same behavior.
I’ve been having issues with the programmatic sign in so switched to manual for now

**Comment by silvolu** [comment] 2015-10-19 21:47
Hi, sorry for the delay in replying. I'm trying to reproduce and investigate the issue, I will update this thread as soon as I find something. Could you let me know which versions of the library are you on?

**Comment by kraghavan-cc** [comment] 2015-10-19 21:54
I am trying it on V 2.3.2

**Comment by kraghavan-cc** [comment] 2015-10-20 00:21
The usecase was to signin, then signout, then signin and do this a few times to see that it fails to sign in with keychain error

**Comment by Argetloum** [comment] 2015-10-26 10:28
+1

**Comment by karthickkumarmr** [comment] 2015-10-26 15:36
Another observation: It seems to be happening only if I run the app from xcode. If I disconnect the phone from XCode and repeat the usecase, it doesn't happen.

**Comment by bigD666** [comment] 2015-10-28 20:37
Fuck this

**Comment by silvolu** [comment] 2015-11-03 16:45
Apologies for the delay in replying; I've been able to reproduce only with xcode attached, as reported by @karthickkumarmr. I believe it could be caused by [this issue](https://forums.developer.apple.com/thread/4743).

**Comment by jlubeck** [comment] 2015-11-03 16:59
I believe that it only happens to me on debug as well. But I haven't pushed to the App Store yet, so I don't have a big user base to test this on. @silvolu, if that issue is the responsible, can we expect something here or we have to wait on Apple to fix that?
Thanks!

**Comment by silvolu** [comment] 2015-11-03 17:24
Unfortunately, there's nothing we can do :/

**Comment by omarojo** [comment] 2015-11-26 00:50
@silvolu What do you mean there is nothing we can do ? Im getting this "keychain error" behaviour too, but does that mean... We just can't test the SignIn functionality while connected to Xcode ? this is crazy :(

**Comment by ianbarber** [comment] 2015-11-30 21:48
@omarojo Silvano is saying there is a bug in general keychain access when the xcode debugger is attached, which we can't easily work around :(

**Comment by santos88** [comment] 2016-01-11 21:27
same problem

**Comment by kraghavan-cc** [comment] 2016-01-11 21:34
I found that it happens only with XCode and that too only with one phone that I use for development . If I changed my phone and tried running from XCode it doesn't happen at all.

**Comment by santihbc** [comment] 2016-01-22 16:33
+1

**Comment by santos88** [comment] 2016-01-22 17:06
I have found a tricky fix, use a delay on the signIn method of the AppDelegate

    func signIn(signIn: GIDSignIn!, didSignInForUser user: GIDGoogleUser!,
        withError error: NSError!) {
            if (error == nil) {
                Lab4TimeUtils.delay(1.0, closure: { () -> () in
                    let nav = self.window?.rootViewController as! UINavigationController
                    if let vc = nav.visibleViewController as? LoginTableVC {
                            vc.googleSiginCallback()
                    }
                })
            } else {
            }
    }

**Comment by s9027059** [comment] 2016-02-24 03:29
Randomly and only happens when App running by XCode.
XCode 7.2.1, iOS 9.2.1, OSX 10.10.5

**Comment by Souf-R** [comment] 2016-02-24 10:29
I had the same issue, here is my Env: (_**XCode: 7.2, iOS: 9.2, OSX: 10.11.2**_).

Just stop the debug from XCode (`Cmd + Shit + .`) then go to your iPhone or Simulator and try to log in with Google.

This works fine ;)

**Comment by mitchellporter** [comment] 2016-03-23 05:46
Anyone still experiencing this? Apple just updated the thread today and said they believe they have fixed this issue, in some circumstances, with the iOS 9.3 update, but that there are still other causes for this that exist.

Here's the thread: https://forums.developer.apple.com/thread/4743

I've been fighting this issue all day. It only started when I deleted the app from my physical iPhone that I use for development. I've tried adding a delay, signing out, running without Xcode attached, and running in release but nothing works.

**Comment by aleclarson** [comment] 2016-09-02 09:33
I'm getting this error in the iOS 10.0 simulator (even when running the Simulator app directly).

Xcode 8.0 beta 6 (8S201h)

**Comment by markcerqueira** [comment] 2016-09-02 18:31
@aleclarson - same here! Also integrating directly into my project, I'm getting a Google Sign-In button that does absolutely nothing when clicked.

**Comment by s9027059** [comment] 2016-09-07 09:50
Have the same issue on iOS10 simulator with XCode8 beta 6.
Found this workaround works by enable keychain sharing of target settings
http://stackoverflow.com/questions/38812761/gidsignin-keychain-error-ios-10-xcode-8

**Comment by SubhojitMandal** [comment] 2016-10-11 14:57
The problem you are trying to solve is connected with keychain access. To fix issue you simply should go to Target->Capabilities and enable keychain sharing

**Comment by ianbarber** [comment] 2016-12-06 21:04
This should be fixed in XCode 8.2 in the simulator AFAIK - let me know if you're seeing the keychain error in that version or above though!

**Closed by ianbarber** 2016-12-06 21:04 UTC

**Comment by sirajudheen53** [comment] 2017-03-02 06:25
I also have the same issue. It is fixed by enabling 'Keychain sharing' in Target capabilities.

**Comment by sugitatestblue** [comment] 2022-07-06 09:03
what is Lab4TimeUtils?
