### ISSUE TITLE
cant install GCM

### ISSUE THREAD

**Issue by mirzadelic** [googlesamples/google-services#22] opened 2015-06-28 15:12 UTC
Hi,
i am getting error when installing gcm from pod file.
I tried without use_framework, and still same error.

Any solution?

![screen shot 2015-06-28 at 17 13 30](https://cloud.githubusercontent.com/assets/1878794/8396872/07e371ea-1db9-11e5-8126-9320220201ab.png)

**Comment by silvolu** [comment] 2015-06-29 23:33
Thanks for reporting this; the problem is discussed in [this CocoaPods issue](https://github.com/CocoaPods/CocoaPods/issues/3194). We're working on a fix, but at this moment I don't know when it will be available.
I will update this issue as soon as I know more.

**Comment by mirzadelic** [comment] 2015-06-29 23:40
Thanks, please write here when there will be version with use_framework.

**Comment by alibasta** [comment] 2015-06-30 09:16
Same here. Thanks for working on it @silvolu !

**Comment by patricks** [comment] 2015-07-02 07:11
+1

**Comment by joel-ipsy** [comment] 2015-07-08 18:16
+1

**Comment by silvolu** [comment] 2015-07-27 17:22
This should be fixed if you update to CocoaPods 0.38.x.
Please reopen if you still have problems.

**Closed by silvolu** 2015-07-27 17:22 UTC

**Comment by jasperwanglin** [comment] 2015-10-09 18:21
I'm still getting this error. CocoaPods 0.38.2.

**Comment by mgerdt** [comment] 2015-10-12 13:06
+1

**Comment by silvolu** [comment] 2015-10-12 20:07
I just tried with 0.39.0 and it works, can you try to update cocoapods or post the podfile you're using?

**Comment by ceoacai** [comment] 2015-11-23 04:00
@mirzadelic did you solve this？ @silvolu I still have this issue when using gRPC

**Comment by mirzadelic** [comment] 2015-11-23 09:14
Just use with 'use_frameworks' and:
'''
	pod 'Google'
	pod 'Google/CloudMessaging'
'''

**Comment by Jyaowen** [comment] 2016-08-24 09:08
The 'Pods-' target has transitive dependencies that include static binaries: (/Pods/OpenSSL/lib/libcrypto.a  and  /Pods/OpenSSL/lib/libssl.a)
