### ISSUE TITLE
Emulator problem

### ISSUE THREAD

**Issue by ManSoSec** [googlesamples/google-services#62] opened 2015-09-04 19:07 UTC
Hi,

I extended a bit the nice app for GCM and I tested the app on 2 mobile devices and it works well. Moreover, I want to do some analysis on emulator and I installed the app on emulator (Intel x86) and added google play services and a google account to the emulator. The app can connect to GCM server and get registration token but when I send a message to the devices, the real mobile devices receive the message but the emulator doesn't receive the message. I tried to send a message just to the emulator but it doesn't work. I tested on both Android API 21 and 23 and it doesn't receive messages. Emulator with Android API 22 has problem with google play services (It may has a bug). The real mobile phone that I tested is Nexus 5 (Android 4.4.2) and Galaxy S6 (Android 5.1.1).

It is about 3 days that I am dying to know what is the problem.

It would be great if you can help me.

Thanks a lot.

**Comment by kroikie** [comment] 2015-09-04 19:23
Could you try the Google APIs emulator with API 19?

**Comment by ManSoSec** [comment] 2015-09-05 09:16
I tried an emulator with API 19 right now but the same problem. I debugged the app and it could verify the registration token but onMessageReceived never called. There is internet in my mobile device but it can be related to handling the internet connection in the emulator. Do you have any suggestion ?
Thanks

**Comment by kroikie** [comment] 2015-09-08 22:24
The sample should work with the emulator, please fill in [this](https://support.google.com/code/contact/gcm_dev_support) form with the details of your situation for further assistance.

**Comment by ManSoSec** [comment] 2015-09-09 11:56
I did it right now.
Thanks

**Comment by kroikie** [comment] 2015-09-09 13:32
@ManSoSec could you give an idea of what changes were made? Have you tried the emulator without the changes?

**Comment by ManSoSec** [comment] 2015-09-11 15:31
@kroikie Sorry for late reply.
I can send you my app if you can give me your email and have time.
The changes I made in emulator is using Google API as the target and also adding a Google account. Should I do anything else ?

Thanks a lot.

**Comment by kroikie** [comment] 2015-09-11 16:13
I was interested in the extensions that were made to the sample. Did you
get things to work before extending?

**Comment by ManSoSec** [comment] 2015-09-11 17:08
honestly, I didn't check before extension. I just added some funstions when the app recieve some messages. There are the changes that I did on the config file:

apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'

android {
    compileSdkVersion 23
    buildToolsVersion '23.0.0'

    defaultConfig {
        applicationId "gcm.play.android.samples.com.gcmquickstart"
        minSdkVersion 9
        targetSdkVersion 21
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    packagingOptions {
        exclude 'LICENSE.txt'
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.google.android.gms:play-services-gcm:7.8.0'
    compile 'com.android.support:appcompat-v7:23.0.0'
    // Testing dependencies
    compile 'com.android.support.test.espresso:espresso-core:2.1'
    compile 'com.android.support.test:runner:0.2'
    compile 'com.android.support:support-annotations:23.0.0'
}

**Comment by kroikie** [comment] 2015-09-11 17:38
Please try the sample in its original form and let us know if you are having the same issues.

**Comment by kroikie** [comment] 2015-09-11 17:39
Please try the original sample and let us know if the same issues occur.

**Comment by ManSoSec** [comment] 2015-09-12 13:41
Today I downloaded and tried the original sample with a new Google cloud project, but it is the same. It is working perfectly on the device but it cannot receive a message from the server in the emulator though it can connect to the server. So, it may be the problem of emulator or my computer. 
I am using the newest version of Android studio that I recently installed and also I have MAC OS X 10.10.2. I don't have any firewall in my computer.

I will ask another guy to install and run the app in another computer to see what is the exact problem. I really appreciate if you know any solution.

Thanks a lot.

**Comment by ManSoSec** [comment] 2015-09-12 14:03
I saw this post (Is the answer true ?) :

http://stackoverflow.com/questions/31475631/is-it-possible-to-receive-gcm-notification-in-android-emulator

**Comment by kroikie** [comment] 2015-09-12 14:16
This is not the case. You should be able to receive GCM with an emulator
with Google APIs. Be sure that when you create the AVD that you choose the
option that has Google APIs.

**Comment by ManSoSec** [comment] 2015-09-12 14:18
Yes, I am sure. If I don't select the Google APIs, I will receive the Google play services error.

**Comment by kroikie** [comment] 2015-09-12 14:24
In that case please follow the link below to get further assistance with
your issue.

https://support.google.com/code/contact/gcm_dev_support

**Comment by ManSoSec** [comment] 2015-09-12 14:28
I've already submitted my request but I haven't received any solution from them.
Thanks

**Comment by silvolu** [comment] 2015-09-14 16:27
@ManSoSec it takes a while to investigate what is going on: sometimes it's quite hard for us to reproduce the issues. You should have received an acknowledgment of your request though, is that not the case?

**Comment by ManSoSec** [comment] 2015-09-14 16:30
Yes, they told me that they are following my case.

Thanks a lot @silvolu :+1:

**Comment by silvolu** [comment] 2015-09-19 00:19
Closing because gcm dev support is following this.

**Closed by silvolu** 2015-09-19 00:19 UTC

**Comment by Elkaa01** [comment] 2016-03-26 18:11
hi,
any feedback/solution for this ? Also have gcm notification working on my phone, but not on the emulator.

**Comment by kroikie** [comment] 2016-03-29 18:26
U I

o
t y
