### ISSUE TITLE
Android Google Choose account Nothing Happen If press Add Account

### ISSUE THREAD

**Issue by thinhlam173** [googlesamples/google-services#372] opened 2018-06-29 10:00 UTC
Issue while implementing Google Sign In

Preconditions
    com.google.android.gms:play-services-auth:15.0.0
    There are some Google account on device.
    Device: Samsung galaxy S7.

Steps to reproduce:

    Launch SignInHubActivity like this:
    Intent intent = Auth.GoogleSignInApi.getSignInIntent(authClient);
    activity.startActivityForResult(intent, requestCode);
  
  The choose account screen show up with list account. Press button Add account, it direct to "Checking info..." - > Add your account screen. Press back button to return to Chose account screen.
  Select 1 account in the list. It return to previous screen, but the screen dimmed without any event. I need to touch the screen or press back button to turn the screen active.

Expected behavior
After select account, it should return to previous screen the data can be catched in onActivityResult

**Comment by samtstern** [comment] 2018-06-29 15:58
This is a duplicate of #358

**Closed by samtstern** 2018-06-29 15:58 UTC

**Comment by thinhlam173** [comment] 2018-06-30 08:38
It may be the same root cause and related to #358 . But I don't think it is a duplicated one. In this case, I press Account account, but do not input email and password for login. Then press back button to return the previous screen to choose exist account.
Another case, after the Choose account screen show up with list email account, then I press home button to turn the app run as background, then resume it. After that, when I select 1 email account in the list. It return to the previous screen, the screen dimmed and nothing happen (the same behaviour with above case).

**Comment by ganjasmara** [comment] 2018-07-06 07:31
Hi, I think we have the same issue (using play-services-auth v15.0.1)
Some bugs that I found:

  - Everytime you go to Google new account activity (you dont have to add the new account, just press back) it always invalidate the previous sign-in activity (resultCode == 0 or RESULT_CANCELED in onActivityResult), hence if you call getResult from Task<GoogleSignInAccount> it will trigger ApiException
  - If you actually add the new account and continue the login process, it will still considered as a continuation of previous sign-in activity (not sure about this), which resulted in RESULT_CANCELED & ApiException too
