### ISSUE TITLE
google-services.json for different productFlavors

### ISSUE THREAD

**Issue by SteveMobile** [googlesamples/google-services#123] opened 2015-12-11 05:30 UTC
Help!!!
my problem is I have different productFlavors with different applicationId/packageName and different GCM Project Id. The 'google-services.json' have to be put at the /app/google-services.json not the flavors folder.

http://stackoverflow.com/questions/30772201/google-services-json-for-different-productflavors

**Comment by samtstern** [comment] 2015-12-11 05:32
Duplicate of #54, please discuss there.

**Closed by samtstern** 2015-12-11 05:32 UTC

**Comment by samtstern** [comment] 2015-12-18 16:24
See #54 for an update.
