### ISSUE TITLE
GMR/ERROR invalid currency code

### ISSUE THREAD

**Issue by travoux** [googlesamples/google-services#215] opened 2016-05-08 13:17 UTC
Why am I getting this error when running the app after integrating with Google Cloud Messaging?
<GMR/ERROR> Cannot record transaction with invalid currency code: (nil)
![screen shot 2016-05-08 at 9 16 41 pm](https://cloud.githubusercontent.com/assets/1425461/15098017/35402cb8-1562-11e6-8dc2-498e5f6a8bcb.png)

**Comment by ggpuglia** [comment] 2016-05-12 20:08
Hi Sajid,

Could you provide the full logging output? I'm interested in the context of this error.

Thanks a lot for reporting this.

**Comment by travoux** [comment] 2016-05-15 03:10
2016-05-15 11:07:44.060 classtree[1402:] <GMR/INFO> App measurement v.2003000 started
2016-05-15 11:07:44.063 classtree[1402:] <GMR/INFO> To enable debug logging set the following application argument: -GMRDebugEnabled (see http://goo.gl/Y0Yjwu)
2016-05-15 11:07:44.126: GCM | GCM library version 1.1.4
2016-05-15 11:07:44.146: GCM | Invalid key in checkin plist: GMSInstanceIDDeviceDataVersion
2016-05-15 11:07:44.337 classtree[1402:] <GMR/INFO> App measurement enabled
Registration Token: *** masked *****
Connected to GCM
2016-05-15 11:07:46.647 classtree[1402:] <GMR/ERROR> Cannot record transaction with invalid currency code: (nil)
2016-05-15 11:07:46.715 classtree[1402:] <GMR/ERROR> Cannot record transaction with invalid currency code: (nil)
2016-05-15 11:07:46.745 classtree[1402:] <GMR/ERROR> Cannot record transaction with invalid currency code: (nil)
2016-05-15 11:07:46.772 classtree[1402:] <GMR/ERROR> Cannot record transaction with invalid currency code: (nil)
2016-05-15 11:07:46.799 classtree[1402:] <GMR/ERROR> Cannot record transaction with invalid currency code: (nil)
2016-05-15 11:07:46.823 classtree[1402:] <GMR/ERROR> Cannot record transaction with invalid currency code: (nil)
2016-05-15 11:07:46.847 classtree[1402:] <GMR/ERROR> Cannot record transaction with invalid currency code: (nil)
2016-05-15 11:07:46.874 classtree[1402:] <GMR/ERROR> Cannot record transaction with invalid currency code: (nil)
2016-05-15 11:07:46.919 classtree[1402:] <GMR/ERROR> Cannot record transaction with invalid currency code: (nil)
2016-05-15 11:07:46.957 classtree[1402:] <GMR/ERROR> Cannot record transaction with invalid currency code: (nil)
2016-05-15 11:07:47.020 classtree[1402:] <GMR/ERROR> Cannot record transaction with invalid currency code: (nil)
2016-05-15 11:07:47.056 classtree[1402:] <GMR/ERROR> Cannot record transaction with invalid currency code: (nil)
2016-05-15 11:07:47.089 classtree[1402:] <GMR/ERROR> Cannot record transaction with invalid currency code: (nil)
2016-05-15 11:07:47.109 classtree[1402:] <GMR/ERROR> Cannot record transaction with invalid currency code: (nil)
2016-05-15 11:07:47.131 classtree[1402:] <GMR/ERROR> Cannot record transaction with invalid currency code: (nil)
2016-05-15 11:07:47.152 classtree[1402:] <GMR/ERROR> Cannot record transaction with invalid currency code: (nil)
2016-05-15 11:07:47.177 classtree[1402:] <GMR/ERROR> Cannot record transaction with invalid currency code: (nil)
2016-05-15 11:07:47.199 classtree[1402:] <GMR/ERROR> Cannot record transaction with invalid currency code: (nil)
2016-05-15 11:07:47.221 classtree[1402:] <GMR/ERROR> Cannot record transaction with invalid currency code: (nil)
2016-05-15 11:07:47.249 classtree[1402:] <GMR/ERROR> Cannot record transaction with invalid currency code: (nil)
2016-05-15 11:07:47.275 classtree[1402:] <GMR/ERROR> Cannot record transaction with invalid currency code: (nil)
2016-05-15 11:07:47.299 classtree[1402:] <GMR/ERROR> Cannot record transaction with invalid currency code: (nil)
2016-05-15 11:07:47.326 classtree[1402:] <GMR/ERROR> Cannot record transaction with invalid currency code: (nil)
2016-05-15 11:07:47.359 classtree[1402:] <GMR/ERROR> Cannot record transaction with invalid currency code: (nil)
2016-05-15 11:07:47.392 classtree[1402:] <GMR/ERROR> Cannot record transaction with invalid currency code: (nil)
2016-05-15 11:07:47.415 classtree[1402:] <GMR/ERROR> Cannot record transaction with invalid currency code: (nil)
2016-05-15 11:07:47.436 classtree[1402:] <GMR/ERROR> Cannot record transaction with invalid currency code: (nil)

**Comment by travoux** [comment] 2016-05-15 03:14
I have used this device to test purchase in-app subscription before using iTunes test user account. But I don't see why gcm support libraries are somehow related to in-app transaction records?

**Comment by travoux** [comment] 2016-05-15 03:17
<img width="1129" alt="screen shot 2016-05-15 at 11 15 36 am" src="https://cloud.githubusercontent.com/assets/1425461/15271826/81c8adcc-1a8e-11e6-9d65-c6c346d0b405.png">


I have used this device to test purchase in-app subscription before. Using iTunes test user account. But I don't see why gcm support libraries are somehow related to the transaction records?

**Comment by ggpuglia** [comment] 2016-05-16 16:58
Hi Sajid,

This is happening because the SDK is receiving "infinite" in-app purchases. This is a long shot, but could you check if you are always calling [[SKPaymentQueue defaultQueue] finishTransaction:transaction].

If you are sure you always calling it, could you enable the verbose mode (-GMRDebugEnabled) argument and post the log output.

Thanks in advance.

**Comment by nathanharig** [comment] 2016-05-17 14:47
I'm in the process of adding in-app purchases for my app, started with the thought that it would be subscription based, but switched it later on. During my subscription-based testing, I had some itunes login problems (test user account) since I have 2-factor and touch-ID enabled. I'm pretty sure this is a very specific error for testers with some of these auth factors. 

The error is not infinite to me, and stops when it prompts me for my itunes store login on the app. The error seems to correspond with the number of times I've launched the simulator. I'm trying to find what is causing this currency call in the first place, but I think the common problem is IAP subscriptions + itunes test user accounts.

**Comment by nathanharig** [comment] 2016-05-17 15:02
I just solved my issue with the following swift code- not sure what yours is in. 

In the viewDidLoad(), run this one then remove/comment it out. It will complete all missing transactions. 

```
for transaction:SKPaymentTransaction in SKPaymentQueue.defaultQueue() .transactions {  // fixes storekit problem
            
            SKPaymentQueue.defaultQueue() .finishTransaction(transaction)
        }
```

Adapted from this- http://stackoverflow.com/a/30948292

**Comment by travoux** [comment] 2016-05-24 13:54
Thanks nathan, that solved the issue. 
But I was wondering why Google Messaging has something to do wi this..

**Comment by samtstern** [comment] 2016-06-28 17:49
@travoux @nathanharig from the discussion it looks like the issue is solved so I am going to close this.  Please re-open if that's not the case.

**Closed by samtstern** 2016-06-28 17:49 UTC

**Comment by abhimuralidharan** [comment] 2016-07-26 10:17
Thanks nathan.This helped.
