### ISSUE TITLE
Class not found when unmarshalling: com.google.android.gms.auth.api.signin.internal.SignInConfiguration

### ISSUE THREAD

**Issue by khaitq7** [googlesamples/google-services#327] opened 2017-06-22 03:36 UTC
### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a Github issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.

### Step 2: Describe your environment

  * Device: _____
  * OS version: _____
  * SDK version: _____
  * [Android] Google Play Services version: _____
  
### Step 3: Describe the problem:
06-22 10:21:46.158 2963-3281/? E/Parcel: Class not found when unmarshalling: com.google.android.gms.auth.api.signin.internal.SignInConfiguration
                                         java.lang.ClassNotFoundException: com.google.android.gms.auth.api.signin.internal.SignInConfiguration
                                             at java.lang.Class.classForName(Native Method)
                                             at java.lang.Class.forName(Class.java:324)
                                             at android.os.Parcel.readParcelableCreator(Parcel.java:2405)
                                             at android.os.Parcel.readParcelable(Parcel.java:2359)
                                             at android.os.Parcel.readValue(Parcel.java:2265)
                                             at android.os.Parcel.readArrayMapInternal(Parcel.java:2620)
                                             at android.os.BaseBundle.unparcel(BaseBundle.java:221)
                                             at android.os.BaseBundle.getString(BaseBundle.java:920)
                                             at android.content.Intent.getStringExtra(Intent.java:6228)
                                             at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2759)
                                             at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:2223)
                                             at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6662)
                                             at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:6395)
                                             at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:174)
                                             at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:4205)
                                             at android.os.Binder.execTransact(Binder.java:453)
                                          Caused by: java.lang.ClassNotFoundException: com.google.android.gms.auth.api.signin.internal.SignInConfiguration
                                             at java.lang.Class.classForName(Native Method)
                                             at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                             at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                             at java.lang.Class.classForName(Native Method) 
                                             at java.lang.Class.forName(Class.java:324) 
                                             at android.os.Parcel.readParcelableCreator(Parcel.java:2405) 
                                             at android.os.Parcel.readParcelable(Parcel.java:2359) 
                                             at android.os.Parcel.readValue(Parcel.java:2265) 
                                             at android.os.Parcel.readArrayMapInternal(Parcel.java:2620) 
                                             at android.os.BaseBundle.unparcel(BaseBundle.java:221) 
                                             at android.os.BaseBundle.getString(BaseBundle.java:920) 
                                             at android.content.Intent.getStringExtra(Intent.java:6228) 
                                             at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2759) 
                                             at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:2223) 
                                             at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6662) 
                                             at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:6395) 
                                             at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:174) 
                                             at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:4205) 
                                             at android.os.Binder.execTransact(Binder.java:453) 
                                          Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

Can't get idToken from google
#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Observed Results:

  * What happened?  This could be a description, log output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by samtstern** [comment] 2017-08-11 01:08
@khaitq7 closing this issue due to old age.  I apologize we never responded.  In the future if you see issues like this please fill out the entire issue template so it's easier for us to debug.

**Closed by samtstern** 2017-08-11 01:08 UTC

**Comment by raiarainne** [comment] 2018-04-09 02:28
I solved this issue.
It was very simple one 
I found another SHA1 key from my google play developer account 
Release management /App signing section 
Here i found My upload certificate and App signing certificate

**Comment by liauli** [comment] 2018-04-16 07:12
@raiarainne which SHA1 do you use? the upload certificate or the app signing ?

**Comment by raiarainne** [comment] 2018-04-16 16:48
@liauli 
I am sorry for delayed reply 
As i mentioned I found the SHA1 from google play store account app releasement section
Release management /App signing section
I hope this will be helped you .

**Comment by rkproject24** [comment] 2018-06-15 06:44
06-15 12:01:39.453 1747-1916/? V/MARsPolicyManager: updatePackagesScore PackageInfo name -- com.google.android.gms
06-15 12:01:39.453 1747-1747/? D/GameManagerService: NotifyRunnable. pkg: com.google.android.gms, type: 4, isMinimized: false, isTunableApp: false
    unexpected mPrevNotiType: -1
06-15 12:01:39.453 1747-1949/? V/WindowManager: Dim Duration=150
06-15 12:01:39.463 1747-3102/? E/Parcel: Class not found when unmarshalling: com.google.android.gms.common.api.Scope
    java.lang.ClassNotFoundException: com.google.android.gms.common.api.Scope
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:324)
        at android.os.Parcel.readParcelableCreator(Parcel.java:2404)
        at android.os.Parcel.readParcelable(Parcel.java:2358)
        at android.os.Parcel.readParcelableArray(Parcel.java:2466)
        at android.os.Parcel.readValue(Parcel.java:2318)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:2614)
        at android.os.BaseBundle.unparcel(BaseBundle.java:221)
        at android.os.BaseBundle.getString(BaseBundle.java:920)
        at android.content.Intent.getStringExtra(Intent.java:6221)
        at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2752)
        at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:2210)
        at com.android.server.am.ActivityManagerService.startActivityInPackage(ActivityManagerService.java:7206)
        at com.android.server.am.PendingIntentRecord.sendInner(PendingIntentRecord.java:310)
        at com.android.server.am.ActivityManagerService.startActivityIntentSender(ActivityManagerService.java:6953)
        at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:296)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:4209)
        at android.os.Binder.execTransact(Binder.java:453)
     Caused by: java.lang.ClassNotFoundException: com.google.android.gms.common.api.Scope
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:324) 
        at android.os.Parcel.readParcelableCreator(Parcel.java:2404) 
        at android.os.Parcel.readParcelable(Parcel.java:2358) 
        at android.os.Parcel.readParcelableArray(Parcel.java:2466) 
        at android.os.Parcel.readValue(Parcel.java:2318) 
        at android.os.Parcel.readArrayMapInternal(Parcel.java:2614) 
        at android.os.BaseBundle.unparcel(BaseBundle.java:221) 
        at android.os.BaseBundle.getString(BaseBundle.java:920) 
        at android.content.Intent.getStringExtra(Intent.java:6221) 
        at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2752) 
        at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:2210) 
        at com.android.server.am.ActivityManagerService.startActivityInPackage(ActivityManagerService.java:7206) 
        at com.android.server.am.PendingIntentRecord.sendInner(PendingIntentRecord.java:310) 
        at com.android.server.am.ActivityManagerService.startActivityIntentSender(ActivityManagerService.java:6953) 
        at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:296) 
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:4209) 
        at android.os.Binder.execTransact(Binder.java:453) 
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
06-15 12:01:39.463 1747-3102/? D/CustomFrequencyManagerService: releaseDVFSLockLocked : Getting Lock type frm List : DVFS_MIN_LIMIT  frequency : 1190400  uid : 1000  pid : 1747  tag : ACTIVITY_RESUME_BOOSTER@7
    acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 1190400  uid : 1000  pid : 1747  pkgName : ACTIVITY_RESUME_BOOSTER@7
    FrequencyrequestList.getNextCStateDisableRequest, index: 0

**Comment by dbehgns211** [comment] 2021-01-18 00:42
nice solution, thank you!
