### ISSUE TITLE
Google SignIn Fails with code 10 (on Android)

### ISSUE THREAD

**Issue by sudarsangp** [googlesamples/google-services#360] opened 2018-04-14 07:05 UTC
### Step 1: Describe your environment
  * Device: Xiaomi Redmi Note 3
  * OS version: 6.0.1
  * MIUI version MIUI Global 9.2

### Step 2: Describe the problem:
Throws Error after choosing Google account

`com.google.samples.quickstart.signin W/SignInActivity: signInResult:failed code=10`

#### Steps to reproduce:

  1. Clone the repository and Launch SignIn App (under Android)
  2. Click SignInActivity
  3. Click Google Sign In button
  4. Choose your Google Account
  5. Logs above error in Logcat

**Comment by ibnahmadbello** [comment] 2018-04-14 16:07
I have also been getting the same error response for the past few days; I have been trying to fixed the problem but no breakthrough and I learnt that the response code (10) means it is a developer problem.
I hope someone can profer a solution here.

**Comment by makeze** [comment] 2018-04-16 12:33
Same issue.

**Comment by samtstern** [comment] 2018-04-16 15:37
Hi all.  Error code 10 is `DEVELOPER_ERROR`:
https://developers.google.com/android/reference/com/google/android/gms/common/api/CommonStatusCodes.html#DEVELOPER_ERROR

This almost certainly means you have not properly registered your SHA1 and Package Name in the Google API console:
https://developers.google.com/identity/sign-in/android/start

If you are 100% sure that you have done this correctly, make sure that your `GoogleSignInOptions` are correct. In particular, make sure the web client ID (if you're using it) belongs to the same project where you registered your package name and SHA1.

I am going to close this issue since that's the best advice I can provide with the limited information above.

**Closed by samtstern** 2018-04-16 15:37 UTC

**Comment by ibnahmadbello** [comment] 2018-04-16 21:11
I just cross-check my SHA1 and discovered a mistake. I have fixed it and the Google sign-in is working as expected. My initial SHA1 was gotten via the terminal while I got the present one via Android studio. Maybe @makeze and @sudarsangp can try something like that if it works.
@samtstern thanks for the tip.

**Comment by sudarsangp** [comment] 2018-04-17 00:49
@samtstern sorry for the trouble it was indeed a misconfiguration issue. @ibnahmadbello thanks for the suggestion.

I still have a question though. I am trying out **SignInActivity** and I don't see any usage of `server_client_id` in **SignInActivity.java**.  Does Google Identity service check whether the project (in google cloud) has a valid **OAuth 2.0 client ID** with the same package name (as the app) in order to allow Signing In?

**Comment by samtstern** [comment] 2018-04-17 01:14
@sudarsangp the web server client ID is used to mint the ID token, so that it's signed for the right "audience".  It's actually not required for signing in, but we recommend that after you sign in you use the ID token to authenticate to your server or to another service (like Firebase Auth)

**Comment by randallto** [comment] 2018-06-27 20:54
I am new to android development and had opted in for google play app signing. My debug release worked fine but when publishing to internal test release it would fail. I realized the app is being resigned upon uploading to google so I registered using signing keys from google play portal and that fixed it. Oddly enough, examining the gradle signing report would only show sha1 for debug builds and not for release builds no matter I had selected the release keystore.  Thankfully for now it is not an issue using google play signing.

**Comment by akashdmahali** [comment] 2018-08-18 18:34
@mike1128  yeah, Facebook too requires 3 keys if you've signed up for Google Play App signing.
Refer to **[this](https://medium.com/@akashmahali/facebook-login-google-sign-in-not-working-on-android-app-in-production-5febd9537f92)** article.

**Comment by erlangp** [comment] 2019-03-11 06:17
thanks @samtstern

**Comment by milogus** [comment] 2019-08-09 18:46
> 
> 
> I just cross-check my SHA1 and discovered a mistake. I have fixed it and the Google sign-in is working as expected. My initial SHA1 was gotten via the terminal while I got the present one via Android studio. Maybe @makeze and @sudarsangp can try something like that if it works.
> @samtstern thanks for the tip.

It works for me, thanks ;)

**Comment by rady-ben** [comment] 2019-08-12 00:23
hi @ibnahmadbello I had the same problem when I was using sh1 generated from the commande line. but when I used android studio I get an other key and it work.
thank you

**Comment by antranvn** [comment] 2019-08-18 09:28
Hello @rady-ben , what is your way to get sha1 from android studio?

**Comment by ripple-xaz** [comment] 2019-08-23 13:11
优秀

**Comment by technologyshare** [comment] 2019-09-15 06:30
This error might happen if you are not using same project at console.developers.google and console.firebase.google.com. If project is same at both console make sure you have add your SHA1 Key properly. Get SHA1 from Android studio.

Open Android Studio
Open your Project
Click on Gradle (From Right Side Panel, you will see Gradle Bar)
Click on Refresh (Click on Refresh from Gradle Bar, you will see List Gradle scripts of your Project)
Click on Your Project (Your Project Name form List (root))
Click on Tasks
Click on Android
Double Click on signingReport (You will get SHA1 and MD5 in Run Bar(Sometimes it will be in Gradle Console))
Select app module from module selection dropdown to run or debug your application   You also need to get google-services.json from firebase console and put into your project.

**Comment by deadsoul44** [comment] 2019-09-15 07:24
@technologyshare there is no Gradle Bar. How to turn it on?

**Comment by antranvn** [comment] 2019-09-15 08:39
@technologyshare: do we need to submit Oauth screen?

**Comment by technologyshare** [comment] 2019-09-15 12:24
![image](https://user-images.githubusercontent.com/42302912/64921516-e6204a00-d7e1-11e9-9a65-e2e99d40e45c.png)
Check in right side

**Comment by technologyshare** [comment] 2019-09-15 12:25
> @technologyshare there is no Gradle Bar. How to turn it on?

![image](https://user-images.githubusercontent.com/42302912/64921522-fb957400-d7e1-11e9-94b4-4244b869100e.png)
Check in right side

**Comment by technologyshare** [comment] 2019-09-15 12:27
> @technologyshare there is no Gradle Bar. How to turn it on?

![image](https://user-images.githubusercontent.com/42302912/64921551-3a2b2e80-d7e2-11e9-9776-1f47f4de1422.png)
Check in the right side

**Comment by technologyshare** [comment] 2019-09-15 13:13
> @technologyshare: do we need to submit Oauth scre

> @technologyshare: do we need to submit Oauth screen?

if you are integrating it from web than you need to pass oauth screen, if you are doing only by phone. No Need

**Comment by akatski316** [comment] 2019-11-06 18:01
When i release my app to playstore in beta mode the same server_client_ID doesn't works and i get error in:

        Task<GoogleSignInAccount> task = GoogleSignIn.getSignedInAccountFromIntent(data);

ApiException: 10

**Comment by yaugenka** [comment] 2020-02-05 14:07
I'm quite new to Android development and was struggling with the error as well. I used Android Studio terminal to get the fingerprint. First I created a debug one by calling `keytool -alias androiddebugkey -keystore %USERPROFILE%\.android\debug.keystore -list -v` and everything worked well. Then I tried a fingerprint from a release keystore generated like so `keytool -keystore path-to-production-keystore -list -v` and got the error. The problem turned out to be in using release key in a debug build. As soon as I generated a release build signed with the same keystore the problem has gone.

**Comment by dk3dani** [comment] 2020-02-05 14:16
I have an application giving this error but it already had the key.jks and I can't reuse it.

**Comment by yaugenka** [comment] 2020-02-05 14:39
It can be reused after deleting previous ids. Go to [credentials](https://console.developers.google.com/apis/credentials) and delete the old `OAuth 2.0 Client IDs`.
Then generate a new fingerprint with `keytool -keystore path-to-production-keystore -list -v` in Android Studio terminal and click on the blue `Configure a project` button at [sign-in start](https://developers.google.com/identity/sign-in/android/start) (step 2). Install the client Id which the wizard will provide you at the end and finally generate a release build signed with the same .jks.

**Comment by sirnornur** [comment] 2020-02-15 13:06
I'm quite new to android development and in my case it was caused by a wrong package name in `app/build.gradle` file.

Although, the tutorial and the configuration page suggests to get the package name from the manifest file, it seems it is checked against the `applicationId` in the `app/build.gradle` file.

There are two places to set the package name I've found so far:
1) `app/src/main/AndroidManifest.xml`
2) `app/build.gradle` `android.defaultConfig.applicationId`

In my case those two names were different. Earlier I had updated the package name in the first file but forgot to update in the `build.gradle` file.

Hope this helps someone.

**Comment by yaugenka** [comment] 2020-02-15 13:54
After release to the store I found signin not working again and it turned out that you need to create a third key with your app's fingerprint from the Play Store developer console because google re-signs published builds with a different certificate.
To sum it up you need to create four OAuth client ids in Google API console:
1 Web client id - this and only this one must be defined in your mobile app.
3 Android client ids (with debug, release and publish fingureprints)

**Comment by Nikoloutsos** [comment] 2020-03-23 14:54
I fixed it by doing the following steps:

1) Go console developer google
2) Click on create a new OAuth client ID
3) Make your Server client id by selecting web application
4) Create another client id by selecting android
5) Use your app's package identifier and SHA1 fingerprint*

* IMPORTANT: you may need to create many android client id for the same app. One for debugging and one for release version. Debugging version has different SHA1 fingerprint than release.

To find out how to get SHA1 fingerprint for your app see previous comments or google it, you will find a lot of resource.

**Comment by Mr-Ramzan** [comment] 2020-06-25 06:53
I hope this might help someone. 
I was facing the same issue after changing Keystore for my Project due to run into a signing problem. 

I was giving SHA1 keys to the firebase console as well as the API console credentials.
![image](https://user-images.githubusercontent.com/36961360/85670342-3bc34480-b6da-11ea-965e-efb6404078e8.png)

I was giving SHA1 generated by circled area but when I put the one from the highlighted one i.e. app module.
It worked.

**Comment by HaripriyaB** [comment] 2020-07-02 18:53
one question..I tried to implement google sign in method without adding my SHA1 key to firebase.. So is it compulsory to add our SHA1 key to firebase for google sign in to work?

**Comment by Mr-Ramzan** [comment] 2020-07-07 11:55
Documentation does no suggest. there might be some other issue  

> one question..I tried to implement google sign in method without adding my SHA1 key to firebase and it was not signing in.. So is it compulsory to add our SHA1 key to firebase for google sign in to work?

**Comment by CYBER-DEVILL** [comment] 2020-07-14 14:40
Yes it is compulsory to add our SHA1 key to firebase and credentials API

**Comment by NehaVerma993** [comment] 2020-07-15 10:18
> This error might happen if you are not using same project at console.developers.google and console.firebase.google.com. If project is same at both console make sure you have add your SHA1 Key properly. Get SHA1 from Android studio.
> 
> Open Android Studio
> Open your Project
> Click on Gradle (From Right Side Panel, you will see Gradle Bar)
> Click on Refresh (Click on Refresh from Gradle Bar, you will see List Gradle scripts of your Project)
> Click on Your Project (Your Project Name form List (root))
> Click on Tasks
> Click on Android
> Double Click on signingReport (You will get SHA1 and MD5 in Run Bar(Sometimes it will be in Gradle Console))
> Select app module from module selection dropdown to run or debug your application   You also need to get google-services.json from firebase console and put into your project.

this is the one and absolute answer every one is looking for, thanks

**Comment by neelspansare** [comment] 2020-10-08 08:07
> I just cross-check my SHA1 and discovered a mistake. I have fixed it and the Google sign-in is working as expected. My initial SHA1 was gotten via the terminal while I got the present one via Android studio. Maybe @makeze and @sudarsangp can try something like that if it works.
> @samtstern thanks for the tip.

Thanks, SHA1 via Android studio worked, terminal SHA1 was not working.

**Comment by jeanraymonddaher** [comment] 2020-10-10 23:23
generate ur key using the gradle task as opposed to getting the key from the terminal . 
that was my issue !

**Comment by IbrahimDisouki** [comment] 2020-11-03 12:42
I thought that I can add `SHA-256` or `SHA1` but you **must** add `SHA1` to get it to work.

**Comment by danielnordh** [comment] 2020-11-19 17:03
We do not use Firebase, just the Outh2 client ID generated in console.developers.google.com

Turned out the issue was that the debug SHA1 fingerprint from keytool was DIFFERENT from the one in gradle signingreport.
The latter worked, the former did not.

**Comment by nareshkumar198** [comment] 2020-12-04 05:41
I fixed this problem,
Go console developer google
Go to My project Which I have to face the problem
Go credentials,
And Open OAuth Client
Change the SHA-1 certificate fingerprint key

**Comment by ahmadbajwa12315** [comment] 2020-12-15 09:41
hello everyone  I have added SH1 in project and console and also configure my project with console. The release APK work fine before uploading to play store after I uploaded in play store it did not work and give me code 10 error. Now you can see there are three keys in console I'm using third one in GoogleSignInOptions here is the code. Help me to resolve this guys.
` GoogleSignInOptions gso = new GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
                .requestIdToken(getString(R.string.AUTH_ID))
                .requestEmail()
                .build();`
![Capture](https://user-images.githubusercontent.com/73605676/102197746-6224a880-3ee3-11eb-8cc2-31989beaa6d4.PNG)

**Comment by Mr-Ramzan** [comment] 2020-12-15 20:39
> hello everyone I have added SH1 in project and console and also configure my project with console. The release APK work fine before uploading to play store after I uploaded in play store it did not work and give me code 10 error. Now you can see there are three keys in console I'm using third one in GoogleSignInOptions here is the code. Help me to resolve this guys.
> ` GoogleSignInOptions gso = new GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN) .requestIdToken(getString(R.string.AUTH_ID)) .requestEmail() .build();`
> ![Capture](https://user-images.githubusercontent.com/73605676/102197746-6224a880-3ee3-11eb-8cc2-31989beaa6d4.PNG)

use the second one and make sure it is not restricted to the platform you are using it in.

**Comment by Mr-Ramzan** [comment] 2020-12-15 20:44
> We do not use Firebase, just the Outh2 client ID generated in console.developers.google.com
> 
> Turned out the issue was that the debug SHA1 fingerprint from keytool was DIFFERENT from the one in gradle signingreport.
> The latter worked, the former did not.

yes, usually android studio generates the SHA1 key using the default Keystore. which changes for production builds as the same Keystore is not used in the signing apk. 
Now if that apk calls for services that have changed SHA1 value gets an error in response.

**Comment by ahmadbajwa12315** [comment] 2020-12-16 09:29
> > hello everyone I have added SH1 in project and console and also configure my project with console. The release APK work fine before uploading to play store after I uploaded in play store it did not work and give me code 10 error. Now you can see there are three keys in console I'm using third one in GoogleSignInOptions here is the code. Help me to resolve this guys.
> > ` GoogleSignInOptions gso = new GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN) .requestIdToken(getString(R.string.AUTH_ID)) .requestEmail() .build();`
> > ![Capture](https://user-images.githubusercontent.com/73605676/102197746-6224a880-3ee3-11eb-8cc2-31989beaa6d4.PNG)
> 
> use the second one and make sure it is not restricted to the platform you are using it in.

After Uploading to play store, Play store generate its own SH1 which we have to replace in second key in google console.

**Comment by ideepakmathur** [comment] 2021-01-09 07:12
Instead of trying everything as stated above, I'm getting the same err 10.

> Generated SHA
> Added to GCP
> Enabled Google Sig-in in Firebase
> Added the Same SHA-1 there

Am I doing it right, please help.

**Comment by jkbngl** [comment] 2021-01-10 09:30
For me the issue was that I created the app in debug mode, but used a production keystore, adding the debug keystore in firebase fixed the issue for me:
```
keytool -alias androiddebugkey -keystore "%USERPROFILE%"\.android\debug.keystore -list -v
```

**Comment by abdullahalamodi** [comment] 2021-02-21 12:04
when I run the app on the emulator it's working fine but when I generate signed apk it's show me this error ??
any advices

**Comment by AndroidDeveloperLB** [comment] 2021-02-21 13:50
@samtstern 

> the web server client ID is used to mint the ID token, so that it's signed for the right "audience". It's actually not required for signing in, but we recommend that after you sign in you use the ID token to authenticate to your server or to another service (like Firebase Auth) if you need to (rather than an access token, which is dangerous)

I needed to use the id-token, so I created a web-application oauth credential, used it and this is how I create the sign-in:

```kt
    fun prepareIntent(context: Context): Intent {
        val googleClientId = context.getString(R.string.server_client_id)
        val options =
            GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
                .requestServerAuthCode(googleClientId)
                //                .requestEmail()
                .build()
        val mSignInClient = GoogleSignIn.getClient(context, options)
        return mSignInClient.signInIntent
    }
```

And to get the id-token, I have this function:

```kt
    @NonNull
    @WorkerThread
    public static String setUp(final Context context, @Nullable final String serverAuthCode) throws IOException {
        final HttpTransport httpTransport = new NetHttpTransport();
        final JacksonFactory jsonFactory = JacksonFactory.getDefaultInstance();
        final String redirectUrl = "urn:ietf:wg:oauth:2.0:oob";
        final String clientId = context.getString(R.string.server_client_id);
        final String clientSecret = context.getString(R.string.client_secret);
        final GoogleTokenResponse tokenResponse = new GoogleAuthorizationCodeTokenRequest(
                httpTransport, jsonFactory,
                clientId, clientSecret,
                serverAuthCode, redirectUrl).execute();
        final String accessToken = tokenResponse.getAccessToken();
        return accessToken;
    }
```

So I call this to reach this function and get it (in background thread) :

```kt
GoogleSignIn.getLastSignedInAccount(this)
val serverAuthCode = result.serverAuthCode
setUp(applicationContext, serverAuthCode)
```

This works, but for some reason, when I run the app and choose the Google account, I also get a dialog of "confirm your choices" :

![image](https://user-images.githubusercontent.com/5357526/108627110-8b6e3180-745c-11eb-849f-c2f91a6375ec.png)

How so?

**Comment by saurabhdtu** [comment] 2021-05-06 17:16
Hi I am facing this issue. https://github.com/flutter/flutter/issues/33393#issuecomment-832855222. I have raised it. Can someone take a look.

**Comment by thuantvDr4** [comment] 2021-06-12 10:33
> Hi all. Error code 10 is `DEVELOPER_ERROR`:
> https://developers.google.com/android/reference/com/google/android/gms/common/api/CommonStatusCodes.html#DEVELOPER_ERROR
> 
> This almost certainly means you have not properly registered your SHA1 and Package Name in the Google API console:
> https://developers.google.com/identity/sign-in/android/start
> 
> If you are 100% sure that you have done this correctly, make sure that your `GoogleSignInOptions` are correct. In particular, make sure the web client ID (if you're using it) belongs to the same project where you registered your package name and SHA1.
> 
> I am going to close this issue since that's the best advice I can provide with the limited information above.

My issue, root cause is SHA1!
we must copy SHA1 at task = "signingReport" and variant  = "debugAndroidTest"
like this =
![image](https://user-images.githubusercontent.com/24288310/121773170-45241600-cba4-11eb-9434-e6e068f83120.png)

**Comment by sahilpatel09** [comment] 2021-07-17 12:30
> I just cross-check my SHA1 and discovered a mistake. I have fixed it and the Google sign-in is working as expected. My initial SHA1 was gotten via the terminal while I got the present one via Android studio. Maybe @makeze and @sudarsangp can try something like that if it works.
> @samtstern thanks for the tip.

Worked for me. Thanks brother

**Comment by nitinsurana** [comment] 2021-08-01 10:57
> After release to the store I found signin not working again and it turned out that you need to create a third key with your app's fingerprint from the Play Store developer console because google re-signs published builds with a different certificate.
> To sum it up you need to create four OAuth client ids in Google API console:
> 1 Web client id - this and only this one must be defined in your mobile app for all build types
> 3 Android client ids (with debug, release and publish fingerprints)

Strange, but this worked!
I literally used the client_id from oauth_2.0_client_ids for type:webApplication in my android source-code.
Earlier, I was using the client_id from oauth_2.0_client_ids for type:android in my android source-code

**Comment by Jmiguel14** [comment] 2021-08-16 03:06
I had the  same problem, I recomend to follow this: https://github.com/CodetrixStudio/CapacitorGoogleAuth/issues/15#issuecomment-515935930
so useful.

**Comment by Anirban-Chand** [comment] 2021-08-21 09:52
> I just cross-check my SHA1 and discovered a mistake. I have fixed it and the Google sign-in is working as expected. My initial SHA1 was gotten via the terminal while I got the present one via Android studio. Maybe @makeze and @sudarsangp can try something like that if it works.
> @samtstern thanks for the tip.

In my case, I tried both from terminal and Android Studio. Both are the same and not working.

**Comment by acrrono** [comment] 2021-12-20 11:44
> After release to the store I found signin not working again and it turned out that you need to create a third key with your app's fingerprint from the Play Store developer console because google re-signs published builds with a different certificate. To sum it up you need to create four OAuth client ids in Google API console: 1 Web client id - this and only this one must be defined in your mobile app for all build types 3 Android client ids (with debug, release and publish fingerprints)


Thank you. This fixed my problem. After i uploaded first bundle to internal testion i started to get an error with google sign in.  What i done to fix that problem:
1. add all of ther cliend ids (for all fingerprints)
2. add play signing fingerprint to firebase console
3. get new google-services.json from firebase console

**Comment by ABHINAVABHISHEK** [comment] 2022-01-15 08:28
Just Use **Web Application** OAuth Client ID 👍👍👍

**Comment by moshequ** [comment] 2022-01-19 16:26
This solved it for me https://www.youtube.com/watch?v=SdYp5JdMvs0

**Comment by erlangparasu** [comment] 2022-01-20 07:40
"Web Application" name confuse me, but it works

**Comment by pfoof** [comment] 2022-02-11 08:15
Also look for this `Key com.google.android.gms.games.APP_ID expected String but value was a java.lang.Float.  The default value <null> was returned.` - yes, use resources like in the guide

**Comment by soniccat** [comment] 2022-10-24 15:23
In my case, everything worked with Client ID from https://console.cloud.google.com. But after adding requestServerAuthCode I started getting errorCode 10 and it turned out that I needed to use oauth_client from fireabse google-services.json which was a different string...

**Comment by fernwehtaylor** [comment] 2022-10-29 04:36
H

**Comment by felixkrautschuk** [comment] 2022-11-03 14:36
I just came across this thread, as I see the same error in our app.

When I add the SHA1 from our release keystore to the Google Cloud Console, the signin process os working when running a release build on device or emulator. When running a debug build on emulator, I see this error code 10.

The other way around, when adding the SHA1 from the debug keystore, the sign in process stops working when running a release build.

So my question is: how can I make sure that I am able to test the login stuff in a debug build AND people using the live app (when it is released on play store) can use the sign in stuff at the same time? As I can only add one SHA1 to the Google Cloud Console.

Btw, I am not using Firebase. Thank you in advance!

**Comment by HzwSunshine** [comment] 2023-04-21 06:53
When I tried to use the New Google Sign-In API (https://developers.google.com/identity/sign-in/android/sign-in-identity), I found that on system versions lower than Android 10, always Error: com.google.android.gms.common.api.ApiException: 10: Caller not whitelisted to call this API., but there is no such error on Android 10 and Android 11 and above phones. I'm currently using Google Sign-In for Android (legacy) (https://developers.google.com/identity/sign-in/android/sign-in) I've also never encountered such an error, I don't understand Why? My SHA1 is configured correctly

**Comment by jaaywags** [comment] 2023-06-20 02:16
I was getting this error and I had checked the SHA's and Web Client stuff were all set up correctly. I must have checked this 20 times. Everything matched in firebase, google developer console, and google-services.json, but yet google sign in was not working.

I finally figured it out and wanted to post this for others (and probably my future self when I run across this again).

My issue was I have 2 firebase projects. One for stage, and one for prod. Stage worked fine but prod did not. Yes, I confirmed I had all the right SHA's set up and everything (sort of). I realized that the SHA I added to firebase was for my production keystore release version, but I was running the app locally in debug mode with my stage keystore file. I quick google on how to run it in release mode locally gave me this command:

`react-native run-android --mode release`

Everything is working now.

**Comment by deepak-exiliensoft** [comment] 2023-08-23 08:17
hii all if you are facing the issue using google login with code 10,then follow the steps below you may find your solution
1.check your project connect to the firebase account
2.if you are connected with firebase account then just add to sha-1 and sha-256 in your firebase account.
3.download the google.json file and put in your app folder in project root folder

hope your problem might be solve
happy coding!

**Comment by stefanobrambilla** [comment] 2024-03-01 14:41
i have a problem with google login ONLY in Production/Android.

i use EXPO
i use it WITHOUT FIREBASE.
i receive in production/android "DEVELOPER_ERROR" error.

Into documentation i see that is always as misconfigured, but the only configuration we have is a fingerprint to add in Google Api Console.

i can't understand which fingerprint add for production.

FINGERPRINT on my google play console
[![enter image description here][1]][1]

FINGERPRINT found in android studio with command gradle signinreport
[![enter image description here][2]][2]

FINGERPRINT found with eas credentials
[![enter image description here][3]][3]
i try every fingerprint with the same result.

thanks in advanced

A help to workaround this problem


  [1]: https://i.stack.imgur.com/ORRSm.png
  [2]: https://i.stack.imgur.com/4LuXh.png
  [3]: https://i.stack.imgur.com/fzAsb.png

**Comment by chuc-efrontiers** [comment] 2024-03-12 14:18
For whom use the AppCenter to distribute the APK. The AppCenter by somehow overrides the release keystore from project, they use their own keystore. You can get this SHA1 from their keystore by downloading the apk and run `keytool -printcert -jarfile 'path_to_apk'`. You'd get the SHA1, then add the new Android Oauth Client ID with this SHA1. Then try again, this fixed my issue. Hope it helps!

**Comment by Us3rL0sT** [comment] 2024-04-07 17:38
> i have a problem with google login ONLY in Production/Android.
> 
> i use EXPO i use it WITHOUT FIREBASE. i receive in production/android "DEVELOPER_ERROR" error.
> 
> Into documentation i see that is always as misconfigured, but the only configuration we have is a fingerprint to add in Google Api Console.
> 
> i can't understand which fingerprint add for production.
> 
> FINGERPRINT on my google play console [![enter image description here](https://camo.githubusercontent.com/fe9723b71170f9aeb2012156854821de52b3389a0be59c2b2f55ba95bf1f9262/68747470733a2f2f692e737461636b2e696d6775722e636f6d2f4f5252536d2e706e67)](https://i.stack.imgur.com/ORRSm.png)
> 
> FINGERPRINT found in android studio with command gradle signinreport [![enter image description here](https://camo.githubusercontent.com/d513c25906d3970b8a0f2d46357956ec16ada61b2e5edb0246d68b604c961d9a/68747470733a2f2f692e737461636b2e696d6775722e636f6d2f344c7558682e706e67)](https://i.stack.imgur.com/4LuXh.png)
> 
> FINGERPRINT found with eas credentials [![enter image description here](https://camo.githubusercontent.com/9b19acf5d53417f3292773dca743b9a00b9678753dfbff703bbad976c61f1a6c/68747470733a2f2f692e737461636b2e696d6775722e636f6d2f667a4173622e706e67)](https://i.stack.imgur.com/fzAsb.png) i try every fingerprint with the same result.
> 
> thanks in advanced
> 
> A help to workaround this problem

hey, u decided it ?

**Comment by shahidkarimi** [comment] 2024-04-19 21:47
This is still a hot issue [samtstern](https://github.com/samtstern). Closing this makes no sense

**Comment by darkokoa** [comment] 2024-06-07 03:55
> After release to the store I found signin not working again and it turned out that you need to create a third key with your app's fingerprint from the Play Store developer console because google re-signs published builds with a different certificate. To sum it up you need to create four OAuth client ids in Google API console: 1 Web client id - this and only this one must be defined in your mobile app for all build types 3 Android client ids (with debug, release and publish fingerprints)

I think the publish fingerprints (sha1) of play store are the easiest for developers to miss.

**Comment by IDENTICOSantiago** [comment] 2024-07-18 19:47
Hello, I have a similar problem, all this time I thought that the problem was when I published my application to the play store that it stopped working, since in APK and emulator it always worked but when I tried to log in with Google from my application it showed me an error 10, but I realized that it is something different and the problem was not with the play store. It's like the system crashes or something because sometimes it works and when it works it works everywhere but when it crashes or I don't know what happens it stops working in all types of environments and throws error 10.

I'm only using Google Cloud for now, but I plan to use FireBase if this problem continues, if anyone knows how I can solve this problem it would be very helpful.

I am using the SHA1 of the release that returns the signinReport of android studio in Google Cloud and from what I see the package name, the fingerprint and the id of the web type client are correct

**Comment by Us3rL0sT** [comment] 2024-07-19 01:14
the solution is to enter 3 sha-1: debug, release, and play market keys into the project setting firebase. 
Enter the key from the play market in the api credentials oauth 2.0, it will be written that it is confirmed. 
Create a web application in oauth 2.0 and use the client - id from this web client.

**Comment by IDENTICOSantiago** [comment] 2024-07-19 13:20
@Us3rL0sT Yes, I managed to solve it by adding another credential with the SHA-1 Certificate of the application signing key from the Google console to Google Cloud, thank you.

**Comment by tananga** [comment] 2024-09-10 20:16
Im trying to login with google but Im always getting this stupid error 10. Im still fighting and today I wasted whole day to deal with it without success. I dont published my app yeat. Im not using firebase. Im using only flutter.

@IDENTICOSantiago can you say exacly what you did?

**Comment by rajaooxx** [comment] 2025-06-11 07:17
> > After release to the store I found signin not working again and it turned out that you need to create a third key with your app's fingerprint from the Play Store developer console because google re-signs published builds with a different certificate. To sum it up you need to create four OAuth client ids in Google API console: 1 Web client id - this and only this one must be defined in your mobile app for all build types 3 Android client ids (with debug, release and publish fingerprints)
> 
> I think the publish fingerprints (sha1) of play store are the easiest for developers to miss.

This save my day
