### ISSUE TITLE
FirebaseInstanceId: Failed to resolve target intent service, skipping classname enforcement; Error while delivering the message: ServiceIntent not found

### ISSUE THREAD

**Issue by kmansoft** [googlesamples/google-services#251] opened 2016-07-16 21:32 UTC
### Step 1: Are you in the right place?

Not sure.

There is an error message in the logcat when running the GCM sample, and yet the messages do get pushed.

There is a bunch of posts on StackOverflow about it, but no good answer.

I'm going to submit in both places, hopefully someone responds.

### Step 2: Describe your environment

  * Device: Samsung S6
  * OS version: 6.0.1
  * SDK version:  24 (I think)
  * [Android] Google Play Services version: 9.2.1
  
### Step 3: Describe the problem:

When the GCM sample app receives push messages (which it does), there is also this in the logcat, on every message:

```
FirebaseInstanceId  E  Failed to resolve target intent service, skipping classname enforcement
E  Error while delivering the message: ServiceIntent not found.
```

#### Steps to reproduce:

  1.  Build GCM sample
  2.  Register with Google Cloud
  3.  Send messages using GcmSender
  4.  Messages are received, but you will also see the above errors in the logcat
  
#### Observed Results:

  * What happened?

Errors in the logcat.
  
#### Expected Results:

  * What did you expect to happen?

I do not expect errors in the logcat.

It looks like they can be ignored (the app does get the pushed messages), but they have severity = Error, what if there is a good reason for this?

What if this causes GCM to work unreliably (some sort of "exponential backoff")?

What causes them? How can I make it so that these errors do not happen?

Oh and since the official word is that GCM will be supported going forward for existing apps -- I'd like to jump on that train too and avoid switching to Firebase messaging.

GCM seems easier to set up and has fewer "magical bits" all around (all the various services / registrations / tokens / APIs and what not). I just need reliable cloud driven push and that's it, nothing else.

#### Relevant Code:

The GCM sample.

**Comment by samtstern** [comment] 2016-07-18 23:37
@kmansoft if you can reproduce this reliably would you mind emailing a bugreport from your device to samstern@google.com?  It would be useful to debug.

Please note a bugreport may contain some personal information so if you don't feel comfortable sending that to us that's OK.

**Comment by kmansoft** [comment] 2016-07-19 17:40
@samtstern I could, but -- are you unable to repro?

**Comment by samtstern** [comment] 2016-07-19 17:42
Yes we are unable to reproduce this in the office.  We have some reports
from Google apps in the wild but they're not as comprehensive as a full bug
report.

**Comment by kmansoft** [comment] 2016-07-19 18:01
Ah. NP, I'll take a look now.

**Comment by kmansoft** [comment] 2016-07-19 18:27
Darn. I'm unable to repro now.

These logcat messages:

```FirebaseInstanceId  E  Failed to resolve target intent service, skipping classname enforcement
E  Error while delivering the message: ServiceIntent not found.
```

are gone.

I even reinstalled the app, which generated a new token, and nothing. Another phone didn't help.

Here is what I'm going to do:

I'm actually working on an app which utilizes GCM.

Was going to use 8.3.0 because of this issue (which doesn't seem to happen with that version), but will use 9.2.1 instead. If the errors come back (in this other app), then I'll generate an adb bugreport.

**Comment by samtstern** [comment] 2016-07-19 18:30
@kmansoft so I would definitely recommend using `9.2.1` and continuing to use GCM in general for the following reasons:

  * These errors are very rare in our experience. In Chrome for Android (with kazillions of installs) we had a tiny number of reports of this issue.  Like I mentioned, no reliable reproduction path.
  * The error, whatever the cause, exists in old versions of the SDK. What's new is that we detect the bad result of the error and log that error message.  This is to help us catch it more in the future.

**Comment by samtstern** [comment] 2016-07-25 22:24
@kmansoft since you're on both threads let's continue this discussion on https://github.com/firebase/quickstart-android/issues/72

I will close this as a duplicate.

**Closed by samtstern** 2016-07-25 22:24 UTC

**Comment by IgorGanapolsky** [comment] 2016-12-22 20:08
@kmansoft So you are recommending using GCM instead of Firebase for simple push messages for developers?  Or did I misunderstand you...

**Comment by kmansoft** [comment] 2016-12-22 20:23
@IgorGanapolsky It just so happens that out app, in production, uses GCM.

Firebase seemed in flux and esp. its wizards "behind the scenes" were doing too much for my personal "alarm threshold" -- and so I went with GCM, at least for the time being (may switch later, but haven't had a reason to so far).

This impression of Firebase was from maybe six months ago, things may be different now.

**Comment by dimple193** [comment] 2019-12-07 11:05
Please Provide Solution.....

 E/FirebaseInstanceId: Failed to resolve target intent service, skipping classname enforcement
 E/FirebaseInstanceId: Error while delivering the message: ServiceIntent not found.

**Comment by abowassm** [comment] 2019-12-07 22:12
I tried on every method that guaranteed the success of the application but failed what should I do

**Comment by BimuratMukhtar** [comment] 2020-01-23 05:36
If you are testing on Xiaomi, it is sometimes impossible to send messages, see this answer also https://stackoverflow.com/questions/58109753/firebaseinstanceid-error-while-delivering-the-message-serviceintent-not-found

**Comment by jordi-additio** [comment] 2021-05-25 09:53
We are facing the same problem. It normally happends when the app has been in background for several hours but it's totaly random: sometimes it happends, others don't. It happends in different devices, not only Xiaomi
