### ISSUE TITLE
Sign-in not translated strings

### ISSUE THREAD

**Issue by mtrakal** [googlesamples/google-services#233] opened 2016-06-03 12:30 UTC
Strings from Signin is not possible translate/get for translate:
- Start sample SignIn app
- Select any activity for login (SignInActivity)
- Click on translated button Sign In (in Czech Přihlásit se)
- Dialog is shown, but there are untranslated: `Choose account for ...` and `Add account` which are not translated.

On screen you can see, that button in background is translated, but not dialog.
![device-2016-06-03-143046](https://cloud.githubusercontent.com/assets/1458891/15778653/d369a3bc-2997-11e6-8aee-91bec3f540a0.png)

**Comment by samtstern** [comment] 2016-06-03 20:33
@mtrakal what is the device language setting?

**Comment by mtrakal** [comment] 2016-06-04 15:31
Device language is set to Czech.
Nexus 5, Android 6.0.1

**Comment by samtstern** [comment] 2016-06-07 22:57
@mtrakal sorry about the slow response here, I will go to the team and find out why these strings are not properly translated.

**Comment by samtstern** [comment] 2016-06-07 23:20
@mtrakal just confirmed the team knows about this and it will be fixed in the next version (they already fixed it, we just have not released that version yet).

Going to close this issue since it's not sample related, thanks!

**Closed by samtstern** 2016-06-07 23:20 UTC
