### ISSUE TITLE
Google analytics GA issue

### ISSUE THREAD

**Issue by maheshwarLigade** [googlesamples/google-services#134] opened 2016-01-04 05:20 UTC
01-04 10:44:32.645 5374-5394/com. E/GAv4: Error storing a property: android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)
01-04 10:44:32.656 5374-5394/com. E/GAv4: Error storing a property: android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)
01-04 10:44:41.267 5374-5394/com. E/GAv4: Error storing a property: android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)
01-04 10:45:37.632 5374-5394/com. E/GAv4: Error storing a property: android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)
01-04 10:45:41.636 5374-5374/com. W/GAv4: syncDispatchLocalHits timed out: java.util.concurrent.TimeoutException
01-04 10:45:42.642 5374-5394/com. E/GAv4: Successfully bound to service but never got onServiceConnected callback
01-04 10:45:42.683 5374-5394/com. E/GAv4: Failed to insert a hit (got -1)
01-04 10:45:42.691 5374-5394/com. E/GAv4: Error storing a property: android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)
01-04 10:45:42.719 5374-5394/com. E/GAv4: Failed to insert a hit (got -1)

**Comment by samtstern** [comment] 2016-01-05 17:27
Can you provide a little more context? Is this crashing your application or is it just something you found in the logs?  Also is there a sequence of events to reproduce this error?

**Comment by maheshwarLigade** [comment] 2016-01-05 17:31
There are no sequence of events to reproduce this error? This issue i face when i used API on emulator with slow network. I try to reproduce it but not happen.

**Comment by samtstern** [comment] 2016-01-05 17:33
I believe this is an internal error to Google Play Services, if you cannot reproduce this I am going to make the team aware and then close this issue.  Please re-open if this is crashing your application or if you can find a way to reproduce it.  Thanks for the report!

**Closed by samtstern** 2016-01-05 17:33 UTC

**Comment by HoodiApp** [comment] 2016-03-02 02:18
Hello, I believe there's a bug in Analytics v4 / Google Play Services 8.4.0
I've set: mTracker.enableExceptionReporting(true);
And whenever I'm forcing an exception just to check if it gets reported, 9 out of 10 times It's not reported due to: W/GAv4: syncDispatchLocalHits timed out: java.util.concurrent.TimeoutException

This is the log:
03-02 06:15:37.179 12225-12225/co.hoodi.dev V/GAv4: Reporting uncaught exception: NullPointerException (@PostDetailsActivity:initActivity:99) {main}
03-02 06:15:41.189 12225-12225/co.hoodi.dev W/GAv4: syncDispatchLocalHits timed out: java.util.concurrent.TimeoutException
03-02 06:15:41.209 12225-12225/co.hoodi.dev V/GAv4: Passing exception to the original handler

Hope it gets resolved soon.
Thanks
