### ISSUE TITLE
ios gcm example, not receiving notification on app quit. 

### ISSUE THREAD

**Issue by promactkaran** [googlesamples/google-services#67] opened 2015-09-16 06:38 UTC
So , we set up everything as mentioned in the getting started document. 

1# we get notification (when sent to a topic) when app is running. 
2# we get notification when app is in background.
3# we never get notification when app is quit. 

Yes we have set background remote notification true also. We have literally tried many things. 
4# When iPhone/iPad is restarted , unless we open the app, we do not receive any notification from GCM. 

Testing on iOS 7.1.2  iPhone 5s , and iPad iOS 8.0

**Comment by silvolu** [comment] 2015-09-16 15:14
@promactkaran looks like a duplicate of #60?

**Comment by InViZz** [comment] 2015-09-21 12:32
had the same problem.
fix it by adding "priority": "high" to push message:
<code>
{
  "registration_ids": ["nYG2y3HGY3...TSR-i3KWNqI"],
  "notification": {
    "title": "Hello, world!",
    "body": "a",
    "badge": 3,
    "sound": "default"
  },
	"priority": "high"
}
</code>

**Comment by silvolu** [comment] 2015-09-21 18:11
Thanks @InViZz! Please check my reply in #60.

**Closed by silvolu** 2015-09-21 18:11 UTC
