### ISSUE TITLE
4.0.0 pods 

### ISSUE THREAD

**Issue by tapz** [googlesamples/google-services#235] opened 2016-06-09 19:12 UTC
Are you going to update the SDK in CocoaPods to 4.0.0?

**Comment by ianbarber** [comment] 2016-07-13 21:51
Which pod are you referring to? The google pod is 3.0.3 https://cocoapods.org/pods/Google

**Comment by tapz** [comment] 2016-07-13 22:42
Google/SignIn. I'm using the most recent pod and been getting this error for weeks:

A new version of the Google Sign-In iOS SDK is available: https://developers.google.com/identity/sign-in/ios/release

**Comment by ianbarber** [comment] 2016-08-09 17:37
3.0.3 in the Google pod depends on GoogleSignIn 4.0 - are you running pod update?

**Comment by tapz** [comment] 2016-08-09 20:22
I tried GoogleSignIn instead of Google/SignIn and now I get the most recent version. Why two names and versions for the same pod?

**Comment by ianbarber** [comment] 2016-08-09 22:31
Ah, see the confusion: they're different pods. Google/SignIn means the subspec "SignIn" of the pod "Google" . GoogleSignIn is the pod "GoogleSignIn". The /SignIn subspec brings in the GoogleSignIn underlying library, so it *should* have worked with a pod update, but clearly didn't. 

The reason for having the subspec is that the "Google" pod basically contains the configuration management stuff if using developers.google.com/mobile/add and the GoogleServices-Info.plist. However, it is quite possible to use GoogleSignIn on its own without that, so it exists as its own lib. 

Glad to hear you have it though!

**Comment by tapz** [comment] 2016-08-10 00:27
Now with "GoogleSignin" instead of "Google/Signin" I get this:

"You have enabled the SignIn service in Developer Console, but it appears as though your Podfile is missing the line: 'pod "Google/SignIn" or you may need to run `pod update` in your project directory."

When calling this:

GGLContext.sharedInstance().configureWithError(&configureError)

**Comment by ianbarber** [comment] 2016-08-10 02:02
Its looking for a category in the Google pod. Could you try what the error recommends, and if you're not getting the latest version, could you post your Podfile?

**Comment by tapz** [comment] 2016-08-10 08:55
Changed GoogleSignIn back to Google/SignIn and pod update says this:

"Installing GoogleSignIn 3.0.0 (was 4.0.0)"

My podfile:

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'MyApp' do
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'
    pod 'Google/CloudMessaging'
    pod 'Google/SignIn'
    pod 'Cloudinary'
    pod 'Alamofire'
    pod 'AlamofireNetworkActivityIndicator'
    pod 'RSKImageCropper'
    pod 'Color-Picker-for-iOS'
    pod 'DGElasticPullToRefresh'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'Instabug'
    pod 'Mixpanel'
    pod 'SnapKit'

    project '../MyApp.xcodeproj'

    target 'MyAppTests' do
        inherit! :search_paths
    end
end

# This is needed because Google libraries don't have BitCode enabled yet.
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      puts "#{target.name}"
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end

**Comment by ianbarber** [comment] 2016-12-06 21:20
Which version of Google pod was it pulling down? Is this still occurring?

**Comment by samtstern** [comment] 2017-01-24 20:10
@ianbarber @tapz this issue is almost 2 months old so I am going to close it for lack of updates.  Please add a comment if this is still a problem and I will be happy to re-open.

**Closed by samtstern** 2017-01-24 20:10 UTC

**Comment by pkc456** [comment] 2017-05-08 09:15
I am also getting the same error (pod 'GoogleSignIn' )

"You have enabled the SignIn service in Developer Console, but it appears as though your Podfile is missing the line: 'pod "Google/SignIn" or you may need to run pod update in your project directory."

When calling this:

GGLContext.sharedInstance().configureWithError(&configureError)

Any solutions please?

**Comment by kachi1227** [comment] 2017-06-27 06:38
Getting the same exact issue and the documentation here: https://developers.google.com/identity/sign-in/ios/sign-in?ver=swift is absolutely not helping. Seems like it's very out-of-date

**Comment by kachi1227** [comment] 2017-06-27 07:02
Spent over an hour trying to figure out what was wrong because the documentation is out of date. To fix this error, you have to remove the `GGLContext.sharedInstance().configureWithError` method and just do this:

`let path = Bundle.main.path(forResource: "GoogleService-Info", ofType: "plist")
  let googleService = NSDictionary(contentsOfFile: path!)!
        
  GIDSignIn.sharedInstance().clientID = googleService.object(forKey: "CLIENT_ID") as! String
  GIDSignIn.sharedInstance().delegate = self
  GIDSignIn.sharedInstance().uiDelegate = self`

This is more-or-less what the sample project does: https://github.com/googlesamples/google-services/blob/master/ios/signin/SignInExampleSwift/AppDelegate.swift

It'd be helpful if the Google Sign-In documentation got updated to reflect the changes that get made to the library. It'd save devs a lot of time.

**Comment by rhys-edwards** [comment] 2018-01-03 22:19
Bumping this as documentation is still outdated..

@kachi1227 Are you able to detail your implementation of this? I've used your code snippet above and I'm still getting the same error.

**Comment by kachi1227** [comment] 2018-01-03 22:47
@rhys-edwards What exactly is your error saying? The code snippet I copied above is what I have in my project. Those lines of code are called in my view controller's viewDidLoad() function.

If you're still having the same issue, make sure that your GoogleService-Info.plist file is in the main bundle. Also, see the snippet from my Podfile below. You might not be downloading the correct pod. I know that was an issue I had run into earlier (I was downloading Google/SignIn instead of GoogleSignIn).

``
# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'Project' do
    pod 'GoogleSignIn'
    target 'ProjectTests' do
        inherit! :search_paths
    end
end

**Comment by rhys-edwards** [comment] 2018-01-03 22:59
@kachi1227 Thanks. Had the wrong pod, unfortunately it's still not working for me.
Are you able to spot where I'm going wrong in the viewcontroller?

````
import UIKit
import GoogleSignIn

@objc(ViewController)

class ViewController: UIViewController, GIDSignInUIDelegate {
    
    // Viewcontroller buttons
    @IBOutlet weak var signInButton: GIDSignInButton!
    @IBOutlet weak var signOutButton: UIButton!
    @IBOutlet weak var disconnectButton: UIButton!
    @IBOutlet weak var statusText: UILabel!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        let path = Bundle.main.path(forResource: "GoogleService-Info", ofType: "plist")
        let googleService = NSDictionary(contentsOfFile: path!)!
        
        GIDSignIn.sharedInstance().clientID = googleService.object(forKey: "CLIENT_ID") as! String
        GIDSignIn.sharedInstance().uiDelegate = self
        
        // Sign in automatically
        GIDSignIn.sharedInstance().signInSilently()
        
        // Something to do with notifications
        NotificationCenter.default.addObserver(self,
                                               selector: #selector(ViewController.receiveToggleAuthUINotification(_:)),
                                               name: NSNotification.Name(rawValue: "ToggleAuthUINotification"),
                                               object: nil)
        
        statusText.text = "Initialized Swift App..."
        toggleAuthUi()
    }
    
    // Sign out tapped
    @IBAction func didTapDisconnect(_ sender: AnyObject) {
        GIDSignIn.sharedInstance().disconnect()
        statusText.text = "Disconnecting"
    }
    
    // Toggle auth
    func toggleAuthUi() {
        if GIDSignIn.sharedInstance().hasAuthInKeychain() {
            signInButton.isHidden = true
            signOutButton.isHidden = false
            disconnectButton.isHidden = false
        } else {
            signInButton.isHidden = false
            signOutButton.isHidden = true
            disconnectButton.isHidden = true
        }
    }
    
    override var preferredStatusBarStyle: UIStatusBarStyle {
        return UIStatusBarStyle.lightContent
    }
    
    deinit {
        NotificationCenter.default.removeObserver(self,
                                                  name: NSNotification.Name(rawValue: "ToggleAuthUINotification"),
                                                  object: nil)
    }
    
    @objc func receiveToggleAuthUINotification(_ notification: NSNotification) {
        if notification.name.rawValue == "ToggleAuthUINotification" {
            self.toggleAuthUi()
            if notification.userInfo != nil {
                guard let userInfo = notification.userInfo as? [String:String] else {return}
                self.statusText.text = userInfo["statusText"]!
            }
        }
    }
}
````

**Comment by kachi1227** [comment] 2018-01-03 23:10
@rhys-edwards no problem. I'm not entirely sure what the problem is based on the code you've included. What you've sent looks similar to what I have; only difference is that I don't call signInSilently(). I would try cleaning your project and rebuilding and seeing if that works. If not, then I'm not really sure what the issue could be.
