### ISSUE TITLE
GIDSignIn.sharedInstance().currentUser is nil after signing in successfully

### ISSUE THREAD

**Issue by edwardIshaq** [googlesamples/google-services#27] opened 2015-07-16 19:26 UTC
I noticed that after I log in GIDSignIn.sharedInstance().currentUser is populated with a GIDGoogleUser but then when I want to check if the user is signed In as they could reach that path without signing in the GIDSignIn.sharedInstance().currentUser is nil again ...

Is there a better way to check if the user is signed in ? or any reason why the singleton GIDSignIn.sharedInstance() would lose its current user value ?

**Comment by gguuss** [comment] 2015-07-23 19:52
I can't think of any reason that the currently signed in user would be nil. Are you using an @gmail account or is this on a Google Apps account?

**Comment by edwardIshaq** [comment] 2015-07-23 20:27
Yes, i’m using my gmail account for testing.
This still happens for some reason …

**Comment by gguuss** [comment] 2015-07-23 23:14
Ahh, you can call  [[GIDSignIn sharedInstance] signInSilently]; to repopulate the signin values after the user has signed in before.

**Comment by edwardIshaq** [comment] 2015-07-24 03:35
I actually do that but then i get an error on signIn:didSignInForUser:withError:  so i have to sign them in again using password …

**Comment by gguuss** [comment] 2015-07-24 05:33
> Is there a better way to check if the user is signed in ?

One approach for checking that the current user is authorized is:

    if ([GIDSignIn sharedInstance].hasAuthInKeychain) {
        NSLog(@"Signed in");
    } else {
        NSLog(@"Not signed in");
    }

If you are conditionally showing UI, this is preferred. If you're using the bearer token from the signed in user, you should probably check with:

    if ([GIDSignIn sharedInstance].currentUser.authentication == nil) {
        NSLog(@"Not authenticated");
    } else {
        NSLog(@"Authenticated");
    }

**Comment by edwardIshaq** [comment] 2015-07-24 21:17
the issue i'm having trouble wrapping my brainz around is the sharedInstance seems to be nullified at some point after the sign in process. Its deleting the singleton purpose of the design ...

**Comment by gguuss** [comment] 2015-07-24 21:46
Can you clarify when the object is being nullified?  For example:

App Loads -> AppDelegate.m ->   Configure shared instance / try silent auth 
If the user is not signed in ...
   Present the View Controller containing the Sign-in button ... 
If the user is signed in ...
  Navigate to new ViewController

NewViewController loads -> ViewControlller.m -> Read profile data*

*(At this point you're saying the profile data has vanished?)

I'm asking because it's possible that somewhere in your application, the GIDSignin object may not be getting configured. You should be configuring the object in your AppDelegate to ensure that every time the app loads, it is configured.

Also, what version of iOS are you testing with?  I am consistently testing with 7.0 / 8.0 ... maybe this is specific to pre-7.0?

**Comment by edwardIshaq** [comment] 2015-07-24 22:01
Hi @gguuss 
So the flow I'm using is:

1- App loads and configures the GIDSignIn
        GIDSignIn.sharedInstance().clientID = GoogleClientID
2- user chooses to login via Google
3- App tries to sign in silently
4- silent sign in succeeds and a user object is obtained from 
signIn:didSignInForUser:withError callback method
5- user navigates into the app view controllers until reaches a point where the app is going to fetch google contacts.
6- which then the app checks for a current user:
        println(GIDSignIn.sharedInstance().currentUser)
        > nil
7- a silent sign in then fired and in case of failure a noisy sign in is fired as appropriate.

I haven't found a pattern for when the currentUser gets nullified yet which is causing me some trouble still.

Please let me know any other details i can provide to track down this issue.

**Comment by gguuss** [comment] 2015-07-24 23:06
Can you reproduce the issue from the Google Sign-In sample? (e.g. `pod try Google` ... signin)

**Comment by samtstern** [comment] 2015-10-14 23:15
Going to close this issue for lack of activity.  Please re-open if you have more information.

**Comment by aventurella** [comment] 2015-11-18 18:39
I get the same issue.   My flow is as follows:
SDK Version 2.4.0 acquired from:
https://developers.google.com/identity/sign-in/ios/sdk/

```swift
func viewDidLoad(){
    super.viewDidLoad()
    initializeFirstView()
}
func initializeFirstView() {
        if GIDSignIn.sharedInstance().hasAuthInKeychain(){
            logInToBackendServerWithAuthIdToken()
        } else{
            region.show(googleLoginView())
        }
}

func logInToBackendServerAuthIdToken{
    let user = GIDSignIn.sharedInstance().currentUser
    print(user) // fatal error: unexpectedly found nil 
}
```

**Comment by omarojo** [comment] 2015-11-26 21:01
@aventurella If I try to do your work around... GIDSignIn.sharedInstance().signInSilently() fails with error -4 because there is not values in the KeyChain. Even though the user was successfully signed before killing the app.

**Comment by crspybits** [comment] 2015-12-20 21:01
I'm getting the same kind of issue. I'm using Swift 2.1, Xcode 7.2 (production), and GoogleSignIn installed as a Cocoapod (https://cocoapods.org/pods/GoogleSignIn; October 2015 release).

In my app delegate, I do:

        var configureError: NSError?
        GGLContext.sharedInstance().configureWithError(&configureError)
        assert(configureError == nil, "Error configuring Google services: \(configureError)")
        
        GIDSignIn.sharedInstance().delegate = self
        
        // Seem to need this for accessing the serverAuthCode. Plus, you seem to need a "fresh" sign-in (not a silent sign-in). PLUS: serverAuthCode is *only* available when you don't do the silent sign in.
        // https://developers.google.com/identity/sign-in/ios/offline-access?hl=en
        GIDSignIn.sharedInstance().serverClientID = "<snip>"
        
        GIDSignIn.sharedInstance().scopes.append("https://www.googleapis.com/auth/drive.file")

The first time the user does a sign-in (i.e., from my UIViewController using GIDSignInUIDelegate), all goes well. I'm able to send the user.authentication.idToken and the serverAuthCode to my server and all goes well. 

Then, after some period of time (e.g., a day later) when I use my app again (I don't do a GIDSignIn.sharedInstance().signInSilently() by default, I just use the IdToken value I obtained before), I get one of two errors on my server (written in Node.js if that matters) when I try a oauth2Client.verifyIdToken: (a) "Not a buffer" or (b) "Token used too late". 

If after this, I do a GIDSignIn.sharedInstance().signInSilently() from my app, I then get: Error Domain=com.google.GIDSignIn Code=-4 
And then, I have to force the user to explicitly sign in again from my UIViewController using GIDSignInUIDelegate. Which is *not* what I want in my final, deployed app.

I'm happy to supply other info. Just ask.

**Comment by montera82** [comment] 2015-12-25 20:13
Any update on this issue ? i am doing a similar thing with @aventurella

**Comment by crspybits** [comment] 2015-12-25 23:35
In my app delegate, after the     

    GIDSignIn.sharedInstance().scopes.append("https://www.googleapis.com/auth/drive.file")

I'm now doing

    GIDSignIn.sharedInstance().signInSilently()

That is, I now do the signInSilently every time immediately as the app is starting up. This seems to have solved the problem. I'm not getting the -4 error any more, and requiring that the user fully sign in. 

The only exception to this is in my XCTest's, but that seems to be limited to some debugging/failure issues with XCTest's.

**Comment by EmanRezk** [comment] 2016-05-22 00:58
I have a problem in my app GIDSignIn.sharedInstance().hasAuthInKeychain() return true in the first time user sign in after close app the open it again it return false. 
can help me please.

**Comment by prathammehta** [comment] 2016-08-18 06:15
@EmanRezk this is the same problem I'm having. Did you find a solution?

**Comment by sahara108** [comment] 2016-08-19 07:44
Same here. I can reproduce this with these steps:

1. Sign in with a gmail account
2. Sign out by calling `GIDSignIn.sharedInstance().disconnect()`
3. Sign in again with the same user.
4. Kill the app.
5. Open the app again that will call `GIDSignIn.sharedInstance().signInSilently()` and you will get `Error Domain=com.google.GIDSignIn Code=-4 "(null)"`.

**Comment by sahara108** [comment] 2016-08-19 07:45
@samtstern can you re-open this please

**Comment by Pranoy1c** [comment] 2016-08-23 05:05
same issue here after moving to version 4.0 of GIDSignIn, the `[GIDSignIn sharedInstance].currentUser` returns nil after the app is relaunched. An additional line of code is needed when the app is relaunched: 

`[[GIDSignIn sharedInstance] signInSilently];`

Note this code should be added only after you have set the clientID,scopes,delegates etc.

**Comment by priyeshmarvi** [comment] 2016-09-09 06:15
Still have an issue and still no work around ... when I sign in and than relaunch the app and try to get sign in instance and its not working ... every time I need to Sign In to get the things working and that's not user friendly. please solve this issue on higher priority.

**Comment by BhavinBhadani** [comment] 2016-09-09 06:44
@samthor just found the work around ...

Whenever you check` if ([GIDSignIn sharedInstance].hasAuthInKeychain)` , before that add your sign in scopes..
  
          GIDSignIn *signin = [GIDSignIn sharedInstance];
    signin.scopes = @[@"https://www.googleapis.com/auth/plus.login",@"https://www.googleapis.com/auth/plus.me"];
        if (signin.hasAuthInKeychain) {
                   NSLog(@"Signed in");
        } else {
                 NSLog(@"Not signed in");
        }

**Comment by EmanRezk** [comment] 2016-10-25 09:58
@BhavinBhadani this way i used it before and it works but now its not work and GIDSignIn.sharedInstance().hasAuthInKeychain() return false after open app again

**Comment by EmanRezk** [comment] 2016-10-25 10:47
The problem with me when signIn then signOut and signIn again this kill app and open it again
1- signIn
2- signOut
3- signIn
4- close app
5- when open app again GIDSignIn.sharedInstance().hasAuthInKeychain() return false

**Comment by haarismuneer** [comment] 2017-03-27 14:43
I'm having the same issue, currentUser is nil even after calling signInSilently(). Below is the relevant code (this is all happening in the AppDelegate's didFinishLaunchingWithOptions). 

```guard let signIn = GIDSignIn.sharedInstance() else { fatalError() }
    signIn.scopes = ["https://www.googleapis.com/auth/plus.stream.read", "https://www.googleapis.com/auth/plus.me", "https://www.googleapis.com/auth/plus.login"]
    signIn.clientID = FIRApp.defaultApp()?.options.clientID
    signIn.delegate = self
    if signIn.hasAuthInKeychain() {
        signIn.signInSilently()
    }

    if signIn.hasAuthInKeychain() || FBSDKAccessToken.current() != nil {

        var token = String()
        if let user = signIn.currentUser{
            token = user.userID
        } else{
            token = FBSDKAccessToken.current().userID
        }
    }
```

The app tries to sign in silently since hasAuthInKeychain returns true. But it skips past the if let statement because currentUser is nil and goes directly into trying to find a FBSDKAccessToken. I've tried all the suggestions I've found including setting the sign-in scopes. Am I missing something?

**Comment by KenShih522** [comment] 2017-04-11 07:14
I had the same issue here but I finally found the answer.

Please check: http://stackoverflow.com/a/43338910/7848589
```
public func resetUserDafault() {

   let userDefaults = UserDefaults.standard

   let dict = UserDefaults.standard.dictionaryRepresentation()

   for key in dict.keys {

       //GoogleSignIn take this key to check previous signin status

       if key == "GID_AppHasRunBefore"{

           continue

       }

       userDefaults.removeObject(forKey: key);

  }

  UserDefaults.standard.synchronize()

}

override func viewDidLoad() {

    super.viewDidLoad()

    //After doing it, my application is working properly now.

    if GIDSignIn.sharedInstance().hasAuthInKeychain() == true{

        GIDSignIn.sharedInstance().signInSilently()

    }
    else{

        //not sign in

    }

}
```

**Comment by morganchen12** [comment] 2017-08-31 23:21
Closing this issue, as it seems to have staled. If this is still a problem for anyone please try updating to the latest version of GIDSignIn and then comment here and I'll reopen the issue.

**Closed** 2017-09-01 18:32 UTC

**Comment by AhmedKhattak** [comment] 2018-06-11 07:01
This issue still exists at this moment.

**Comment by spife129** [comment] 2018-07-17 20:54
The issue is that if Auth.auth().signInAndRetrieveData is not called after sign in, currentUser will be non-nil for one moment and next time will be nil until the aforementioned call is completed.
```
let credential = GoogleAuthProvider.credential(withIDToken: authentication.idToken, 											   accessToken: authentication.accessToken)		
Auth.auth().signInAndRetrieveData(with: credential) { (authResult, error) in
```

**Comment by eduardothiesen** [comment] 2020-01-22 17:27
I'm having a similar issue with version 5.0.2. 

My flow is: 
SignIn Successfully;
Closes the app;
Open the app;

GIDSignIn.sharedInstance().hasPreviousSignIn() returns nil
GIDSignIn.sharedInstance().restorePreviousSignIn() returns error
GIDSignIn.sharedInstance().currentUser returns nil

Anything I have to do to maintain the current session in memory? 
Thanks in advance.

**Comment by soiferman** [comment] 2020-03-05 16:38
This issue still exists. After relaunching the app, the GIDSignIn.sharedInstance()?.currentUser always returns nil.

**Comment by prof18** [comment] 2020-10-14 07:10
Did anyone manage to solve this issue? It happens to me as well!

**Comment by dan-ryan** [comment] 2020-11-18 00:46
I'm doing this and user is still nil. 
```
			let googleSignIn = GIDSignIn.sharedInstance()!
			if (googleSignIn.hasPreviousSignIn()) {
				googleSignIn.restorePreviousSignIn()
			}
			let user = googleSignIn.currentUser
```

**Comment by eduardothiesen** [comment] 2020-11-18 01:03
I discovered that in any part of the code you call 
`UserDefaults.standard.removePersistentDomain(forName: Bundle.main.bundleIdentifier!)`
it erases the current user. At least this was my personal problem. Hope it helps someone!
