### ISSUE TITLE
GCM registration is not ready with auth credentials

### ISSUE THREAD

**Issue by iamakashrao** [googlesamples/google-services#242] opened 2016-06-24 23:28 UTC
GCM registration is not ready with auth credentials

**Comment by samtstern** [comment] 2016-06-28 17:31
@iamakashrao it is not clear what the issue is here.  When posting an issue please provide a full description of the problem, the minimal code used to reproduce the problem, and any relevant device logs.

I am going to close this issue as I can't help with what's here, but please re-open the issue if you are able to provide the information requested.

**Closed by samtstern** 2016-06-28 17:31 UTC

**Comment by arvindrajachourasiya** [comment] 2017-11-18 09:02
Hi,
I am facing the same issue in xamarin ios app. while launching the app it is getting crash.  and showing those errors-
You have enabled the CloudMessaging service in Developer Console, but it appears as though your Podfile is missing the line: 'pod "Google/CloudMessaging" or you may need to run `pod update` in your project directory.
2017-11-18   Failed to configure Google: Missing expected subspecs.
2017-11-18  GCM | GCM library version 1.1.4
2017-11-18  <GMR/INFO> App measurement v.2003000 started
2017-11-18 <GMR/INFO> To enable debug logging set the following application argument: -GMRDebugEnabled (see http://goo.gl/Y0Yjwu)
Resolved pending breakpoint at 'AppDelegate.cs:218,5' to void edTheSIS.iOS.AppDelegate.<>c.<RegisterForRemoteNotification>b__25_0 (bool approved, Foundation.NSError err) [0x00006].
Resolved pending breakpoint at 'AppDelegate.cs:220,4' to void edTheSIS.iOS.AppDelegate.<>c.<RegisterForRemoteNotification>b__25_0 (bool approved, Foundation.NSError err) [0x00012].
2017-11-18 14:12:53.747 edTheSIS.iOS[339:] <GMR/INFO> App measurement enabled
Thread started:  #7
2017-11-18 14:13:01.033: GCM | GCM registration is not ready with auth credentials
2017-11-18 14:13:05.239 edTheSIS.iOS[339:84837] critical: Stacktrace:

Please help how to solve it
