### ISSUE TITLE
GoogleApiClient app-indexing memory leak?

### ISSUE THREAD

**Issue by finneapps** [googlesamples/google-services#176] opened 2016-02-24 07:16 UTC
Hi. Android Studio tells me that I have a memory leak in my app. I am using AppIndexing and It all seems to relate to GoogleApiClient. If I remove the call to GoogleApiClient from my app, then there is no memory leak detected.

please take a look on this stackoverflow post:
http://stackoverflow.com/questions/35308231/memory-leak-with-googleapiclient-detected-by-android-studio

So, is it a real memory leak or should I ignore it?

**Comment by soufianeEssabbane** [comment] 2016-02-26 17:36
it's seems to be causing memory leak even in iOS

**Comment by ianbarber** [comment] 2016-02-29 21:19
Hmm, the code in the SO post looks ok at first glance to me. Have you confirmed the onStop is being called in your test?

**Comment by samtstern** [comment] 2016-06-28 17:45
I am closing this issue as the last activity was by @ianbarber a few months ago.  If there is still more to resolve here, please re-open and continue the discussion.

**Closed by samtstern** 2016-06-28 17:45 UTC

**Comment by finneapps** [comment] 2016-06-28 17:50
Problem was resolved by using apllication context when creating the GoogleApiClient

**Comment by saantiaguilera** [comment] 2017-01-14 01:21
But this is still a memory leak, since the `GoogleApiClient.Builder` wont release the `Context` reference, even after calling `disconnect()`. If you build it with activities that are accessed a lot (like a user profile), it makes OOMs way too easy to reproduce.

Either have this properly documented or ask for an `Application` instead of a `Context` when building the `GoogleApiClient.Builder` please :)

**Comment by samtstern** [comment] 2017-01-20 23:14
@saantiaguilera you're right that we should document this.  I will bring this issue to the attention of the App Indexing team to get a fix in as well.
